-- RSR Deevena Food Court shared billing database
-- Run this in Supabase SQL Editor after creating a project.

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  bill_no bigint not null unique,
  bill_date timestamptz not null default now(),
  items jsonb not null,
  total numeric(12,2) not null,
  payment text not null check (payment in ('Cash','UPI','Card')),
  created_at timestamptz not null default now()
);

create index if not exists bills_bill_date_idx on public.bills (bill_date desc);
create index if not exists bills_bill_no_idx on public.bills (bill_no desc);

alter table public.bills enable row level security;

drop policy if exists "public can read bills" on public.bills;
create policy "public can read bills"
on public.bills for select
to anon
using (true);

drop policy if exists "public can insert bills" on public.bills;
create policy "public can insert bills"
on public.bills for insert
to anon
with check (true);

create sequence if not exists public.rsr_bill_no_seq start with 1001;

-- Keep the sequence at least at 1001. The function returns the next
-- number atomically, so multiple phones cannot receive the same bill number.
create or replace function public.next_rsr_bill_no()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  n bigint;
begin
  n := nextval('public.rsr_bill_no_seq');
  return n;
end;
$$;

grant execute on function public.next_rsr_bill_no() to anon;
