-- RSR Deevena Food Court shared billing database
-- Run this in Supabase SQL Editor after creating a project.

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  bill_no bigint not null unique,
  bill_date timestamptz not null default now(),
  items jsonb not null,
  total numeric(12,2) not null,
  payment text not null check (payment in ('Cash','UPI','Card')),
  created_at timestamptz not null default now()
);

create index if not exists bills_bill_date_idx on public.bills (bill_date desc);
create index if not exists bills_bill_no_idx on public.bills (bill_no desc);

alter table public.bills enable row level security;

grant select on table public.bills to anon;

drop policy if exists "public can read bills" on public.bills;
create policy "public can read bills"
on public.bills for select
to anon
using (true);

drop policy if exists "public can insert bills" on public.bills;
create policy "public can insert bills"
on public.bills for insert
to anon
with check (true);

create or replace function public.create_rsr_bill(
  p_items jsonb,
  p_total numeric,
  p_payment text,
  p_bill_date timestamptz default now()
)
returns table (
  id bigint,
  bill_no bigint,
  bill_date timestamptz,
  items jsonb,
  total numeric,
  payment text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $
declare
  n bigint;
begin
  if p_payment not in ('Cash','UPI','Card') then
    raise exception 'Invalid payment method';
  end if;

  -- Serialize bill-number allocation so six phones cannot receive the same number.
  perform pg_advisory_xact_lock(923456789);
  select coalesce(max(b.bill_no), 1000) + 1 into n from public.bills b;

  return query
  insert into public.bills (bill_no, bill_date, items, total, payment)
  values (n, coalesce(p_bill_date, now()), p_items, p_total, p_payment)
  returning bills.id, bills.bill_no, bills.bill_date, bills.items,
            bills.total, bills.payment, bills.created_at;
end;
$;

grant execute on function public.create_rsr_bill(jsonb,numeric,text,timestamptz) to anon;
